server:
  port: 9090

spring:
  application:
    name: admin-server
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:8888

  security:
    user:
      name: ${ADMIN_USER:admin}
      password: ${ADMIN_PASSWORD:admin-secret}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USER:eureka-admin}:${EUREKA_PASSWORD:eureka-secret-2024}@${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.investrac: INFO
