apiVersion: v1
kind: ConfigMap
metadata:
  name: investrac-config
  namespace: investrac
data:
  EUREKA_HOST:         "eureka-server"
  CONFIG_SERVER_HOST:  "config-server"
  KAFKA_SERVERS:       "kafka-service:9092"
  REDIS_HOST:          "redis-service"
  ZIPKIN_HOST:         "zipkin-service"
  ADMIN_SERVER_HOST:   "admin-server"
  EUREKA_USER:         "eureka-admin"
  CONFIG_SERVER_USER:  "config-admin"
  ADMIN_USER:          "admin"
  DB_USER:             "investrac"
  TZ:                  "Asia/Kolkata"
