apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: investrac

resources:
  # Config
  - config/namespace.yaml
  - config/secrets.yaml
  - config/configmap.yaml
  - config/network-policy.yaml

  # Infrastructure
  - infrastructure/eureka-server.yaml
  - infrastructure/api-gateway.yaml

  # Services
  - services/auth-service.yaml
  - services/user-service.yaml
  - services/wallet-service.yaml
  - services/transaction-service.yaml
  - services/account-service.yaml
  - services/portfolio-service.yaml
  - services/ai-service.yaml
  - services/notification-service.yaml

images:
  - name: investrac/auth-service
    newTag: "1.0.0"
  - name: investrac/user-service
    newTag: "1.0.0"
  - name: investrac/wallet-service
    newTag: "1.0.0"
  - name: investrac/transaction-service
    newTag: "1.0.0"
  - name: investrac/account-service
    newTag: "1.0.0"
  - name: investrac/portfolio-service
    newTag: "1.0.0"
  - name: investrac/ai-service
    newTag: "1.0.0"
  - name: investrac/notification-service
    newTag: "1.0.0"
  - name: investrac/api-gateway
    newTag: "1.0.0"
  - name: investrac/eureka-server
    newTag: "1.0.0"
